import type {
	Action,
	AssignedIssue,
	AssignedIssuesResult,
	ColorPalette,
	Dashboard,
	GitStatusCache,
	Issue,
	IssueDependency,
	KeyboardShortcut,
	LabelShapeMapping,
	NotificationConfig,
	OverviewWorkspaceData,
	PrunableIssue,
	Session,
	SyncAllResult,
	WindowWorkspaceBinding,
} from '$lib/types/generated';

// ─── Stable IDs ───────────────────────────────────────────────────────────────

const DASHBOARD_GROVEKEEPER = 'mock-dash-grovekeeper';
const DASHBOARD_PORTFOLIO = 'mock-dash-portfolio';

const ISSUE_AUTH_MIDDLEWARE = 'mock-issue-auth';
const ISSUE_DARK_MODE = 'mock-issue-dark-mode';
const ISSUE_PERF_AUDIT = 'mock-issue-perf';
const ISSUE_CI_PIPELINE = 'mock-issue-ci';
const ISSUE_ONBOARDING = 'mock-issue-onboarding';
const ISSUE_ARCHIVED = 'mock-issue-archived';
const ISSUE_API_GATEWAY = 'mock-issue-api-gateway';
const ISSUE_INTEGRATION_TESTS = 'mock-issue-integration-tests';
const ISSUE_WORKTREE_PENDING = 'mock-issue-wt-pending';
const ISSUE_WORKTREE_FAILED = 'mock-issue-wt-failed';
const ISSUE_PR_MERGED = 'mock-issue-pr-merged';
const ISSUE_CONFLICT = 'mock-issue-conflict';

const PALETTE_VIVID = 'palette-vivid';

// ─── Dashboards ───────────────────────────────────────────────────────────────

export const MOCK_DASHBOARDS: Dashboard[] = [
	{
		id: DASHBOARD_GROVEKEEPER,
		name: 'Grovekeeper',
		type: 'repo',
		github_repo: 'MartinoPolo/Grovekeeper',
		local_folder: 'C:/_MP_projects/Grovekeeper',
		default_base_branch: 'dev',
		worktree_parent_folder: 'C:/_MP_projects/worktrees',
		color_palette_id: PALETTE_VIVID,
		accent_color: '#62874b',
		default_shape: 'oak',
		priorities_enabled: true,
	},
	{
		id: DASHBOARD_PORTFOLIO,
		name: 'All Projects',
		type: 'portfolio',
		github_repo: null,
		local_folder: null,
		default_base_branch: null,
		worktree_parent_folder: null,
		color_palette_id: null,
		accent_color: null,
		default_shape: 'pine',
		priorities_enabled: true,
	},
];

// ─── Issues ───────────────────────────────────────────────────────────────────

export const MOCK_ISSUES: Issue[] = [
	{
		id: ISSUE_AUTH_MIDDLEWARE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Refactor auth middleware for OAuth2',
		priority: 'high',
		color: '#ef4444',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/42',
		github_issue_number: 42,
		branch_name: '42-refactor-auth-middleware',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/42-refactor-auth-middleware',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"auth","color":"#ef4444"},{"name":"security","color":"#f59e0b"}]',
		sort_order: 0,
		created_at: '2026-04-28T10:00:00Z',
	},
	{
		id: ISSUE_DARK_MODE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Implement dark mode toggle',
		priority: 'medium',
		color: '#8b5cf6',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/55',
		github_issue_number: 55,
		branch_name: '55-dark-mode-toggle',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/55-dark-mode-toggle',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: 'pnpm dev',
		dev_server_port: 1420,
		dev_server_pid: null,
		browser_url: 'http://localhost:1420',
		labels: '[{"name":"ui","color":"#8b5cf6"},{"name":"theme","color":"#6366f1"}]',
		sort_order: 1,
		created_at: '2026-04-29T14:30:00Z',
	},
	{
		id: ISSUE_PERF_AUDIT,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Performance audit: reduce bundle size',
		priority: 'low',
		color: '#f97316',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/63',
		github_issue_number: 63,
		branch_name: '63-perf-audit-bundle',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"performance","color":"#f97316"}]',
		sort_order: 2,
		created_at: '2026-04-30T09:15:00Z',
	},
	{
		id: ISSUE_CI_PIPELINE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Fix CI pipeline timeout on E2E tests',
		priority: 'high',
		color: '#ef4444',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/71',
		github_issue_number: 71,
		branch_name: '71-ci-timeout-fix',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/71-ci-timeout-fix',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"ci","color":"#06b6d4"},{"name":"testing","color":"#14b8a6"}]',
		sort_order: 3,
		created_at: '2026-05-01T08:00:00Z',
	},
	{
		id: ISSUE_ONBOARDING,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Add onboarding wizard for new users',
		priority: 'medium',
		color: '#10b981',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/78',
		github_issue_number: 78,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"ui","color":"#8b5cf6"},{"name":"onboarding","color":"#10b981"}]',
		sort_order: 4,
		created_at: '2026-05-02T11:45:00Z',
	},
	{
		id: ISSUE_API_GATEWAY,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Build API gateway with rate limiting',
		priority: 'medium',
		color: '#8b5cf6',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/85',
		github_issue_number: 85,
		branch_name: '85-api-gateway',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"backend","color":"#8b5cf6"}]',
		sort_order: 5,
		created_at: '2026-05-03T10:00:00Z',
	},
	{
		id: ISSUE_INTEGRATION_TESTS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Add integration test suite for API',
		priority: 'low',
		color: '#06b6d4',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/92',
		github_issue_number: 92,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"testing","color":"#14b8a6"}]',
		sort_order: 6,
		created_at: '2026-05-04T14:00:00Z',
	},
	{
		id: ISSUE_WORKTREE_PENDING,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Setup worktree for API integration',
		priority: 'medium',
		color: '#06b6d4',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/100',
		github_issue_number: 100,
		branch_name: '100-api-integration',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'pending',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"api","color":"#06b6d4"}]',
		sort_order: 7,
		created_at: '2026-05-03T10:00:00Z',
	},
	{
		id: ISSUE_WORKTREE_FAILED,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Database schema migration',
		priority: 'high',
		color: '#f43f5e',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/102',
		github_issue_number: 102,
		branch_name: '102-db-migration',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'failed',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"database","color":"#f43f5e"},{"name":"migration","color":"#a855f7"}]',
		sort_order: 8,
		created_at: '2026-05-03T11:00:00Z',
	},
	{
		id: ISSUE_PR_MERGED,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Add rate limiting to API endpoints',
		priority: 'low',
		color: '#84cc16',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/105',
		github_issue_number: 105,
		branch_name: '105-rate-limiting',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/105-rate-limiting',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"api","color":"#06b6d4"},{"name":"security","color":"#f59e0b"}]',
		sort_order: 9,
		created_at: '2026-05-03T12:00:00Z',
	},
	{
		id: ISSUE_CONFLICT,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Refactor routing with type-safe paths',
		priority: 'top',
		color: '#d946ef',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/108',
		github_issue_number: 108,
		branch_name: '108-type-safe-routing',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/108-type-safe-routing',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"refactor","color":"#6b7280"},{"name":"routing","color":"#d946ef"}]',
		sort_order: 10,
		created_at: '2026-05-03T13:00:00Z',
	},
	{
		id: ISSUE_ARCHIVED,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Migrate to Tailwind v4',
		priority: null,
		color: '#6b7280',
		status: 'archived',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/30',
		github_issue_number: 30,
		branch_name: '30-tailwind-v4-migration',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"refactor","color":"#6b7280"}]',
		sort_order: 5,
		created_at: '2026-04-15T16:00:00Z',
	},
];

// ─── Issue Dependencies ───────────────────────────────────────────────────────

export const MOCK_ISSUE_DEPENDENCIES: IssueDependency[] = [
	{
		id: 'mock-dep-1',
		blocker_issue_id: ISSUE_AUTH_MIDDLEWARE,
		blocked_issue_id: ISSUE_ONBOARDING,
	},
	{
		id: 'mock-dep-2',
		blocker_issue_id: ISSUE_AUTH_MIDDLEWARE,
		blocked_issue_id: ISSUE_API_GATEWAY,
	},
	{
		id: 'mock-dep-3',
		blocker_issue_id: ISSUE_API_GATEWAY,
		blocked_issue_id: ISSUE_INTEGRATION_TESTS,
	},
];

// ─── Sessions ─────────────────────────────────────────────────────────────────

export const MOCK_SESSIONS: Session[] = [
	{
		id: 'mock-session-running',
		issue_id: ISSUE_AUTH_MIDDLEWARE,
		provider: 'claude-code',
		state: 'running',
		pid: 12345,
		cli_session_id: 'ses_abc123',
		started_at: '2026-05-03T09:00:00Z',
		ended_at: null,
		cost_usd: 0.42,
		token_count: 15200,
		original_intent: 'Refactor the auth middleware to use OAuth2 tokens',
		last_prompt: 'Continue with the token refresh logic',
		last_response_summary: 'Implementing token refresh with exponential backoff...',
		execution_phase: 'tdd',
		source: 'spawned',
		working_directory: 'C:/_MP_projects/worktrees/42-refactor-auth-middleware',
	},
	{
		id: 'mock-session-needs-input',
		issue_id: ISSUE_DARK_MODE,
		provider: 'claude-code',
		state: 'needs-input',
		pid: 12346,
		cli_session_id: 'ses_def456',
		started_at: '2026-05-03T08:30:00Z',
		ended_at: null,
		cost_usd: 0.28,
		token_count: 9800,
		original_intent: 'Add dark mode toggle component',
		last_prompt: null,
		last_response_summary: 'Should the toggle persist preference to localStorage or DB?',
		execution_phase: 'analyzing',
		source: 'spawned',
		working_directory: 'C:/_MP_projects/worktrees/55-dark-mode-toggle',
	},
	{
		id: 'mock-session-finished',
		issue_id: ISSUE_CI_PIPELINE,
		provider: 'claude-code',
		state: 'finished',
		pid: null,
		cli_session_id: 'ses_ghi789',
		started_at: '2026-05-02T14:00:00Z',
		ended_at: '2026-05-02T14:45:00Z',
		cost_usd: 1.05,
		token_count: 42000,
		original_intent: 'Fix E2E test timeouts in CI',
		last_prompt: null,
		last_response_summary:
			'Increased Playwright timeout and added retry logic for flaky tests.',
		execution_phase: 'none',
		source: 'adopted',
		working_directory: 'C:/_MP_projects/worktrees/71-ci-timeout-fix',
	},
	{
		id: 'mock-session-codex',
		issue_id: ISSUE_DARK_MODE,
		provider: 'codex',
		state: 'running',
		pid: 12347,
		cli_session_id: 'thread_0199a213',
		started_at: '2026-05-04T10:00:00Z',
		ended_at: null,
		cost_usd: 0.15,
		token_count: 5400,
		original_intent: 'Generate unit tests for dark mode toggle',
		last_prompt: 'Add tests for theme persistence',
		last_response_summary: 'Writing vitest specs for localStorage theme save/load...',
		execution_phase: 'tdd',
		source: 'spawned',
		working_directory: 'C:/_MP_projects/worktrees/55-dark-mode-toggle',
	},
];

// ─── Actions ──────────────────────────────────────────────────────────────────

export const MOCK_ACTIONS: Action[] = [
	{
		id: 'mock-action-editor',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Open in VS Code',
		icon: 'code',
		command_template: 'code {{worktree_folder}}',
		sort_order: 0,
		visible: true,
	},
	{
		id: 'mock-action-tests',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Run Tests',
		icon: 'test-tube',
		command_template: 'cd {{worktree_folder}} && pnpm test',
		sort_order: 1,
		visible: true,
	},
	{
		id: 'mock-action-deploy',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Deploy Preview',
		icon: 'rocket',
		command_template: 'cd {{worktree_folder}} && pnpm deploy:preview',
		sort_order: 2,
		visible: true,
	},
];

// ─── Color Palettes ──────────────────────────────────────────────────────────

export const MOCK_COLOR_PALETTES: ColorPalette[] = [
	{
		id: PALETTE_VIVID,
		name: 'Vivid',
		colors: [
			'#ef4444',
			'#f97316',
			'#eab308',
			'#22c55e',
			'#10b981',
			'#06b6d4',
			'#3b82f6',
			'#8b5cf6',
		],
		is_built_in: true,
	},
	{
		id: 'palette-pastel',
		name: 'Pastel',
		colors: [
			'#fca5a5',
			'#fdba74',
			'#fde047',
			'#86efac',
			'#6ee7b7',
			'#67e8f9',
			'#93c5fd',
			'#c4b5fd',
		],
		is_built_in: true,
	},
];

// ─── Git Status Caches ───────────────────────────────────────────────────────

export const MOCK_GIT_STATUSES: GitStatusCache[] = [
	{
		issue_id: ISSUE_AUTH_MIDDLEWARE,
		branch_status: 'active',
		pr_state: 'open',
		pr_number: 101,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/101',
		github_issue_state: 'open',
		behind_base_count: 2,
		merge_conflict: false,
		has_local_changes: true,
		ahead_remote_count: 3,
		fetched_at: '2026-05-03T09:00:00Z',
	},
	{
		issue_id: ISSUE_DARK_MODE,
		branch_status: 'active',
		pr_state: 'draft',
		pr_number: 105,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/105',
		github_issue_state: 'open',
		behind_base_count: 0,
		merge_conflict: false,
		has_local_changes: false,
		ahead_remote_count: 0,
		fetched_at: '2026-05-03T08:30:00Z',
	},
	{
		issue_id: ISSUE_CI_PIPELINE,
		branch_status: 'active',
		pr_state: 'approved',
		pr_number: 110,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/110',
		github_issue_state: 'open',
		behind_base_count: 0,
		merge_conflict: false,
		has_local_changes: false,
		ahead_remote_count: 0,
		fetched_at: '2026-05-03T08:00:00Z',
	},
	{
		issue_id: ISSUE_PR_MERGED,
		branch_status: 'active',
		pr_state: 'merged',
		pr_number: 115,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/115',
		github_issue_state: 'closed',
		behind_base_count: 0,
		merge_conflict: false,
		has_local_changes: false,
		ahead_remote_count: 0,
		fetched_at: '2026-05-03T12:00:00Z',
	},
	{
		issue_id: ISSUE_CONFLICT,
		branch_status: 'active',
		pr_state: 'review-requested',
		pr_number: 118,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/118',
		github_issue_state: 'open',
		behind_base_count: 7,
		merge_conflict: true,
		has_local_changes: true,
		ahead_remote_count: 5,
		fetched_at: '2026-05-03T13:00:00Z',
	},
];

// ─── Label Shape Mappings ─────────────────────────────────────────────────────

export const MOCK_LABEL_SHAPE_MAPPINGS: LabelShapeMapping[] = [
	{
		id: 'mock-lsm-auth',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		label_name: 'auth',
		tree_shape: 'oak',
		color: '#ef4444',
		priority_order: 0,
	},
	{
		id: 'mock-lsm-ui',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		label_name: 'ui',
		tree_shape: 'birch',
		color: '#8b5cf6',
		priority_order: 1,
	},
	{
		id: 'mock-lsm-perf',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		label_name: 'performance',
		tree_shape: 'willow',
		color: '#f97316',
		priority_order: 2,
	},
];

// ─── Notification Configs ─────────────────────────────────────────────────────

export const MOCK_NOTIFICATION_CONFIGS: NotificationConfig[] = [
	{
		event_type: 'needs-input',
		sound_enabled: true,
		sound_file: null,
		toast_enabled: true,
		window_flash_enabled: true,
	},
	{
		event_type: 'needs-review',
		sound_enabled: true,
		sound_file: null,
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'finished',
		sound_enabled: true,
		sound_file: null,
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'errored',
		sound_enabled: true,
		sound_file: null,
		toast_enabled: true,
		window_flash_enabled: true,
	},
	{
		event_type: 'pr-ready',
		sound_enabled: false,
		sound_file: null,
		toast_enabled: true,
		window_flash_enabled: false,
	},
];

// ─── Assigned Issues ──────────────────────────────────────────────────────────

const MOCK_ASSIGNED_ISSUES: AssignedIssue[] = [
	{
		number: 42,
		title: 'Refactor auth middleware for OAuth2',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/42',
		labels: [{ name: 'auth', color: 'ef4444' }],
	},
	{
		number: 55,
		title: 'Implement dark mode toggle',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/55',
		labels: [
			{ name: 'ui', color: '8b5cf6' },
			{ name: 'theme', color: '6366f1' },
		],
	},
	{
		number: 78,
		title: 'Add onboarding wizard for new users',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/78',
		labels: [{ name: 'ui', color: '8b5cf6' }],
	},
];

export const MOCK_ASSIGNED_ISSUES_RESULT: AssignedIssuesResult = {
	issues: MOCK_ASSIGNED_ISSUES,
	has_more: false,
};

// ─── Overview Data ────────────────────────────────────────────────────────────

export const MOCK_OVERVIEW_DATA: OverviewWorkspaceData[] = [
	{
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Grovekeeper',
		github_repo: 'MartinoPolo/Grovekeeper',
		local_folder: 'C:/_MP_projects/Grovekeeper',
		color_palette_id: PALETTE_VIVID,
		accent_color: '#62874b',
		open_issue_count: 5,
		active_session_count: 2,
		last_activity: '2026-05-03T09:05:00Z',
		total_cost_usd: 1.75,
	},
];

// ─── Window Bindings ──────────────────────────────────────────────────────────

export const MOCK_WINDOW_BINDINGS: WindowWorkspaceBinding[] = [];

// ─── Keyboard Shortcuts ───────────────────────────────────────────────────────

export const MOCK_CUSTOM_BINDINGS: KeyboardShortcut[] = [];

// ─── Prunable Issues ──────────────────────────────────────────────────────────

export const MOCK_PRUNABLE_ISSUES: PrunableIssue[] = [];

// ─── Sync Result ──────────────────────────────────────────────────────────────

export const MOCK_SYNC_RESULT: SyncAllResult = { synced_count: 3, errors: [] };

// ─── Usage Dashboard ──────────────────────────────────────────────────────────

export const MOCK_USAGE_DASHBOARD = {
	stats: {
		total_cost_usd: 12.84,
		session_count: 47,
		one_shot_rate: 74.0,
		cache_hit_ratio: 68.0,
		cost_delta_percent: -18.0,
		session_count_delta: 9,
	},
	daily_costs: Array.from({ length: 30 }, (_, i) => ({
		date: `2026-04-${String(i + 1).padStart(2, '0')}`,
		cost_usd: Math.random() * 1.5,
		session_count: Math.floor(Math.random() * 5) + 1,
	})),
	activity_breakdown: [
		{ category: 'coding', cost_usd: 4.2, turn_count: 89, one_shot_percent: 82.0 },
		{ category: 'debugging', cost_usd: 2.8, turn_count: 52, one_shot_percent: 61.0 },
		{ category: 'refactoring', cost_usd: 1.9, turn_count: 31, one_shot_percent: 90.0 },
		{ category: 'testing', cost_usd: 1.4, turn_count: 28, one_shot_percent: 78.0 },
		{ category: 'exploration', cost_usd: 1.1, turn_count: 24, one_shot_percent: 0.0 },
		{ category: 'planning', cost_usd: 0.8, turn_count: 18, one_shot_percent: 0.0 },
		{ category: 'conversation', cost_usd: 0.64, turn_count: 15, one_shot_percent: 0.0 },
	],
	top_sessions: [
		{
			session_id: 's1',
			issue_name: 'Auth middleware rewrite',
			issue_number: 42,
			cost_usd: 1.42,
			turn_count: 28,
			tool_call_count: 67,
			started_at: '2026-04-24T14:30:00Z',
		},
		{
			session_id: 's2',
			issue_name: 'Dark mode toggle',
			issue_number: 15,
			cost_usd: 0.98,
			turn_count: 15,
			tool_call_count: 34,
			started_at: '2026-04-22T10:00:00Z',
		},
		{
			session_id: 's3',
			issue_name: 'Perf audit',
			issue_number: 7,
			cost_usd: 0.87,
			turn_count: 12,
			tool_call_count: 29,
			started_at: '2026-04-20T09:00:00Z',
		},
		{
			session_id: 's4',
			issue_name: 'CI pipeline fix',
			issue_number: 3,
			cost_usd: 0.76,
			turn_count: 9,
			tool_call_count: 22,
			started_at: '2026-04-18T16:00:00Z',
		},
		{
			session_id: 's5',
			issue_name: null,
			issue_number: null,
			cost_usd: 0.54,
			turn_count: 7,
			tool_call_count: 15,
			started_at: '2026-04-15T11:00:00Z',
		},
	],
	tool_usage: [
		{ tool_name: 'Read', call_count: 342 },
		{ tool_name: 'Edit', call_count: 187 },
		{ tool_name: 'Bash', call_count: 156 },
		{ tool_name: 'Grep', call_count: 134 },
		{ tool_name: 'Write', call_count: 89 },
		{ tool_name: 'Glob', call_count: 76 },
		{ tool_name: 'Agent', call_count: 42 },
		{ tool_name: 'WebSearch', call_count: 18 },
		{ tool_name: 'mcp__svelte', call_count: 12 },
		{ tool_name: 'TaskCreate', call_count: 8 },
	],
};

export const MOCK_ACHIEVEMENTS = [
	{
		kind: 'first-seed',
		display_name: 'First Seed',
		description: 'Created your first issue',
		threshold: 1,
		progress: 1,
		unlocked_at: '2026-04-01T10:00:00Z',
	},
	{
		kind: 'planted-10-trees',
		display_name: 'Planted 10 Trees',
		description: 'Created 10 issues',
		threshold: 10,
		progress: 12,
		unlocked_at: '2026-04-15T14:00:00Z',
	},
	{
		kind: 'planted-50-trees',
		display_name: 'Planted 50 Trees',
		description: 'Created 50 issues',
		threshold: 50,
		progress: 12,
		unlocked_at: null,
	},
	{
		kind: 'green-thumb',
		display_name: 'Green Thumb',
		description: 'Completed 10 sessions via Grovekeeper',
		threshold: 10,
		progress: 10,
		unlocked_at: '2026-04-20T16:00:00Z',
	},
	{
		kind: 'forest-keeper',
		display_name: 'Forest Keeper',
		description: 'Resolved 5 HITL issues',
		threshold: 5,
		progress: 3,
		unlocked_at: null,
	},
	{
		kind: 'conflict-resolver',
		display_name: 'Conflict Resolver',
		description: 'Auto-resolved 3 merge conflicts',
		threshold: 3,
		progress: 1,
		unlocked_at: null,
	},
	{
		kind: 'one-shot-wonder',
		display_name: 'One-Shot Wonder',
		description: '5 sessions with 100% one-shot rate',
		threshold: 5,
		progress: 5,
		unlocked_at: '2026-05-01T09:00:00Z',
	},
	{
		kind: 'cache-master',
		display_name: 'Cache Master',
		description: 'A session with 90%+ cache hit ratio',
		threshold: 1,
		progress: 1,
		unlocked_at: '2026-04-25T12:00:00Z',
	},
	{
		kind: 'big-spender',
		display_name: 'Big Spender',
		description: 'Spent $100 total on AI sessions',
		threshold: 100,
		progress: 12,
		unlocked_at: null,
	},
	{
		kind: 'speed-runner',
		display_name: 'Speed Runner',
		description: 'Completed a session in under 60 seconds',
		threshold: 1,
		progress: 0,
		unlocked_at: null,
	},
];

export const MOCK_IMPORT_SUMMARY = {
	providers: [
		{ provider: 'claude-code', sessions_imported: 142, sessions_skipped: 0 },
		{ provider: 'cursor', sessions_imported: 89, sessions_skipped: 3 },
		{ provider: 'codex', sessions_imported: 16, sessions_skipped: 0 },
	],
	total_sessions: 247,
	total_skipped: 3,
};
