import type {
	Action,
	AssignedIssue,
	AssignedIssuesResult,
	ColorPalette,
	Dashboard,
	GitStatusCache,
	Issue,
	IssueDependency,
	KeyboardShortcut,
	LabelShapeMapping,
	NotificationConfig,
	OverviewWorkspaceData,
	PrunableIssue,
	Session,
	SyncAllResult,
	WindowWorkspaceBinding,
	WorkspaceCommand,
} from '$lib/types/generated';

// ─── Stable IDs ───────────────────────────────────────────────────────────────

const DASHBOARD_GROVEKEEPER = 'mock-dash-grovekeeper';
const DASHBOARD_PORTFOLIO = 'mock-dash-portfolio';

const ISSUE_AUTH_MIDDLEWARE = 'mock-issue-auth';
const ISSUE_DARK_MODE = 'mock-issue-dark-mode';
const ISSUE_PERF_AUDIT = 'mock-issue-perf';
const ISSUE_CI_PIPELINE = 'mock-issue-ci';
const ISSUE_ONBOARDING = 'mock-issue-onboarding';
const ISSUE_ARCHIVED = 'mock-issue-archived';
const ISSUE_API_GATEWAY = 'mock-issue-api-gateway';
const ISSUE_INTEGRATION_TESTS = 'mock-issue-integration-tests';
const ISSUE_WORKTREE_PENDING = 'mock-issue-wt-pending';
const ISSUE_WORKTREE_FAILED = 'mock-issue-wt-failed';
const ISSUE_PR_MERGED = 'mock-issue-pr-merged';
const ISSUE_CONFLICT = 'mock-issue-conflict';

const PRD_NOTIFICATIONS = 'mock-prd-notifications';
const PRD_SESSIONS = 'mock-prd-sessions';
const PRD_AI_CONFIG = 'mock-prd-ai-config';

const ISSUE_NOTIF_ENGINE = 'mock-issue-notif-engine';
const ISSUE_NOTIF_PACKS = 'mock-issue-notif-packs';
const ISSUE_NOTIF_SETTINGS = 'mock-issue-notif-settings';
const ISSUE_NOTIF_SOUND_FIX = 'mock-issue-notif-sound-fix';
const ISSUE_NOTIF_PACK_CREATOR = 'mock-issue-notif-pack-creator';
const ISSUE_NOTIF_TRIGGERS = 'mock-issue-notif-triggers';
const ISSUE_SESS_ADAPTER = 'mock-issue-sess-adapter';
const ISSUE_SESS_TOOL_CARDS = 'mock-issue-sess-tool-cards';
const ISSUE_SESS_APPROVAL = 'mock-issue-sess-approval';
const ISSUE_AI_CONFIG_UI = 'mock-issue-ai-config-ui';
const ISSUE_AI_SKILL_CONTROLS = 'mock-issue-ai-skill-controls';

const PALETTE_VIVID = 'palette-vivid';

// ─── Dashboards ───────────────────────────────────────────────────────────────

export const MOCK_DASHBOARDS: Dashboard[] = [
	{
		id: DASHBOARD_GROVEKEEPER,
		name: 'Grovekeeper',
		type: 'repo',
		github_repo: 'MartinoPolo/Grovekeeper',
		local_folder: 'C:/_MP_projects/Grovekeeper',
		default_base_branch: 'dev',
		worktree_parent_folder: 'C:/_MP_projects/worktrees',
		color_palette_id: PALETTE_VIVID,
		accent_color: '#62874b',
		chart_color_theme: 'monochrome',
		default_shape: 'oak',
		priorities_enabled: true,
		status: 'active',
	},
	{
		id: DASHBOARD_PORTFOLIO,
		name: 'All Projects',
		type: 'portfolio',
		github_repo: null,
		local_folder: null,
		default_base_branch: null,
		worktree_parent_folder: null,
		color_palette_id: null,
		accent_color: null,
		chart_color_theme: null,
		default_shape: 'pine',
		priorities_enabled: true,
		status: 'active',
	},
];

// ─── Issues ───────────────────────────────────────────────────────────────────

export const MOCK_ISSUES: Issue[] = [
	{
		id: ISSUE_AUTH_MIDDLEWARE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Refactor auth middleware for OAuth2',
		priority: 'high',
		color: '#ef4444',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/42',
		github_issue_number: 42,
		branch_name: '42-refactor-auth-middleware',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/42-refactor-auth-middleware',
		worktree_state: 'active',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"auth","color":"#ef4444"},{"name":"security","color":"#f59e0b"}]',
		sort_order: 0,
		created_at: '2026-04-28T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_DARK_MODE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Implement dark mode toggle',
		priority: 'medium',
		color: '#8b5cf6',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/55',
		github_issue_number: 55,
		branch_name: '55-dark-mode-toggle',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/55-dark-mode-toggle',
		worktree_state: 'active',
		parent_issue_id: PRD_SESSIONS,
		editor_folder: null,
		dev_server_command: 'pnpm dev',
		dev_server_port: 1420,
		dev_server_pid: null,
		browser_url: 'http://localhost:1420',
		labels: '[{"name":"ui","color":"#8b5cf6"},{"name":"theme","color":"#6366f1"}]',
		sort_order: 1,
		created_at: '2026-04-29T14:30:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_PERF_AUDIT,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Performance audit: reduce bundle size',
		priority: 'low',
		color: '#f97316',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/63',
		github_issue_number: 63,
		branch_name: '63-perf-audit-bundle',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"performance","color":"#f97316"}]',
		sort_order: 2,
		created_at: '2026-04-30T09:15:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_CI_PIPELINE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Fix CI pipeline timeout on E2E tests',
		priority: 'high',
		color: '#ef4444',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/71',
		github_issue_number: 71,
		branch_name: '71-ci-timeout-fix',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/71-ci-timeout-fix',
		worktree_state: 'active',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"ci","color":"#06b6d4"},{"name":"testing","color":"#14b8a6"}]',
		sort_order: 3,
		created_at: '2026-05-01T08:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_ONBOARDING,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Add onboarding wizard for new users',
		priority: 'medium',
		color: '#10b981',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/78',
		github_issue_number: 78,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"ui","color":"#8b5cf6"},{"name":"onboarding","color":"#10b981"}]',
		sort_order: 4,
		created_at: '2026-05-02T11:45:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_API_GATEWAY,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Build API gateway with rate limiting',
		priority: 'medium',
		color: '#8b5cf6',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/85',
		github_issue_number: 85,
		branch_name: '85-api-gateway',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"backend","color":"#8b5cf6"}]',
		sort_order: 5,
		created_at: '2026-05-03T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_INTEGRATION_TESTS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Add integration test suite for API',
		priority: 'low',
		color: '#06b6d4',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/92',
		github_issue_number: 92,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"testing","color":"#14b8a6"}]',
		sort_order: 6,
		created_at: '2026-05-04T14:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_WORKTREE_PENDING,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Setup worktree for API integration',
		priority: 'medium',
		color: '#06b6d4',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/100',
		github_issue_number: 100,
		branch_name: '100-api-integration',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'pending',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"api","color":"#06b6d4"}]',
		sort_order: 7,
		created_at: '2026-05-03T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_WORKTREE_FAILED,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Database schema migration',
		priority: 'high',
		color: '#f43f5e',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/102',
		github_issue_number: 102,
		branch_name: '102-db-migration',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'failed',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"database","color":"#f43f5e"},{"name":"migration","color":"#a855f7"}]',
		sort_order: 8,
		created_at: '2026-05-03T11:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_PR_MERGED,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Add rate limiting to API endpoints',
		priority: 'low',
		color: '#84cc16',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/105',
		github_issue_number: 105,
		branch_name: '105-rate-limiting',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/105-rate-limiting',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"api","color":"#06b6d4"},{"name":"security","color":"#f59e0b"}]',
		sort_order: 9,
		created_at: '2026-05-03T12:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_CONFLICT,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Refactor routing with type-safe paths',
		priority: 'top',
		color: '#d946ef',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/108',
		github_issue_number: 108,
		branch_name: '108-type-safe-routing',
		base_branch: 'dev',
		worktree_folder: 'C:/_MP_projects/worktrees/108-type-safe-routing',
		worktree_state: 'active',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"refactor","color":"#6b7280"},{"name":"routing","color":"#d946ef"}]',
		sort_order: 10,
		created_at: '2026-05-03T13:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_ARCHIVED,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Migrate to Tailwind v4',
		priority: null,
		color: '#6b7280',
		status: 'archived',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/30',
		github_issue_number: 30,
		branch_name: '30-tailwind-v4-migration',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"refactor","color":"#6b7280"}]',
		sort_order: 5,
		created_at: '2026-04-15T16:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},

	// ─── PRD: Notifications & Sounds (mirrors GitHub PRD #95) ────────────────
	{
		id: PRD_NOTIFICATIONS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'PRD: Notifications & Sounds',
		priority: 'high',
		color: '#f59e0b',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/95',
		github_issue_number: 95,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"prd","color":"#a855f7"},{"name":"area:platform","color":"#06b6d4"}]',
		sort_order: 11,
		created_at: '2026-04-20T09:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_NOTIF_ENGINE,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Build notification engine',
		priority: 'medium',
		color: null,
		status: 'archived',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/235',
		github_issue_number: 235,
		branch_name: '235-notification-engine',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'removed',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:platform","color":"#06b6d4"}]',
		sort_order: 12,
		created_at: '2026-04-20T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_NOTIF_PACKS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Character pack system with per-issue assignment',
		priority: 'medium',
		color: null,
		status: 'archived',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/236',
		github_issue_number: 236,
		branch_name: '236-character-packs',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'removed',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:ui","color":"#d4c5f9"}]',
		sort_order: 13,
		created_at: '2026-04-21T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_NOTIF_SETTINGS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Notification settings UI overhaul',
		priority: 'medium',
		color: null,
		status: 'archived',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/237',
		github_issue_number: 237,
		branch_name: '237-notification-settings-ui',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'removed',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:ui","color":"#d4c5f9"}]',
		sort_order: 14,
		created_at: '2026-04-22T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_NOTIF_SOUND_FIX,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Fix sound engine (Tokio crash, errors, MP3, rotation)',
		priority: 'high',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/264',
		github_issue_number: 264,
		branch_name: '264-fix-sound-engine',
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:platform","color":"#06b6d4"}]',
		sort_order: 15,
		created_at: '2026-05-08T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_NOTIF_PACK_CREATOR,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Character pack creator + bulk import + avatars',
		priority: 'medium',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/265',
		github_issue_number: 265,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:ui","color":"#d4c5f9"},{"name":"area:platform","color":"#06b6d4"},{"name":"design-needed","color":"#f97316"}]',
		sort_order: 16,
		created_at: '2026-05-08T11:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_NOTIF_TRIGGERS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Wire 4 session notification event triggers',
		priority: 'medium',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/266',
		github_issue_number: 266,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_NOTIFICATIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:platform","color":"#06b6d4"}]',
		sort_order: 17,
		created_at: '2026-05-08T12:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},

	// ─── PRD: Sessions ───────────────────────────────────────────────────────
	{
		id: PRD_SESSIONS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'PRD: Multi-Provider Sessions',
		priority: 'high',
		color: '#3b82f6',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/90',
		github_issue_number: 90,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"prd","color":"#a855f7"},{"name":"area:session","color":"#7057ff"}]',
		sort_order: 18,
		created_at: '2026-04-25T09:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_SESS_ADAPTER,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Provider adapter pattern (Claude/Cursor/Codex/Aider)',
		priority: 'top',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/150',
		github_issue_number: 150,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_SESSIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:rust","color":"#dea584"}]',
		sort_order: 19,
		created_at: '2026-04-25T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_SESS_TOOL_CARDS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Session tool cards UI',
		priority: 'high',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/151',
		github_issue_number: 151,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_SESSIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"HITL","color":"#f59e0b"},{"name":"area:ui","color":"#d4c5f9"}]',
		sort_order: 20,
		created_at: '2026-04-25T11:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_SESS_APPROVAL,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Approval flow fix',
		priority: 'medium',
		color: null,
		status: 'archived',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/152',
		github_issue_number: 152,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'removed',
		parent_issue_id: PRD_SESSIONS,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"area:rust","color":"#dea584"}]',
		sort_order: 21,
		created_at: '2026-04-26T11:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},

	// ─── PRD: AI Configuration ──────────────────────────────────────────────
	{
		id: PRD_AI_CONFIG,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'PRD: AI Configuration',
		priority: 'medium',
		color: '#10b981',
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/94',
		github_issue_number: 94,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: null,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"prd","color":"#a855f7"},{"name":"area:ui","color":"#d4c5f9"}]',
		sort_order: 22,
		created_at: '2026-04-28T09:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_AI_CONFIG_UI,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'AI configuration page with discovery engine',
		priority: 'medium',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/244',
		github_issue_number: 244,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_AI_CONFIG,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:ui","color":"#d4c5f9"}]',
		sort_order: 23,
		created_at: '2026-05-01T10:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
	{
		id: ISSUE_AI_SKILL_CONTROLS,
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Skill controls with enable/disable',
		priority: 'low',
		color: null,
		status: 'active',
		github_issue_url: 'https://github.com/MartinoPolo/Grovekeeper/issues/245',
		github_issue_number: 245,
		branch_name: null,
		base_branch: 'dev',
		worktree_folder: null,
		worktree_state: 'none',
		parent_issue_id: PRD_AI_CONFIG,
		editor_folder: null,
		dev_server_command: null,
		dev_server_port: null,
		dev_server_pid: null,
		browser_url: null,
		labels: '[{"name":"task","color":"#22c55e"},{"name":"AFK","color":"#1d76db"},{"name":"area:ui","color":"#d4c5f9"}]',
		sort_order: 24,
		created_at: '2026-05-01T11:00:00Z',
		character_pack_id: null,
		character_avatar: null,
		is_sound_muted: false,
	},
];

// ─── Issue Dependencies ───────────────────────────────────────────────────────

export const MOCK_ISSUE_DEPENDENCIES: IssueDependency[] = [
	{
		id: 'mock-dep-1',
		blocker_issue_id: ISSUE_AUTH_MIDDLEWARE,
		blocked_issue_id: ISSUE_ONBOARDING,
	},
	{
		id: 'mock-dep-2',
		blocker_issue_id: ISSUE_AUTH_MIDDLEWARE,
		blocked_issue_id: ISSUE_API_GATEWAY,
	},
	{
		id: 'mock-dep-3',
		blocker_issue_id: ISSUE_API_GATEWAY,
		blocked_issue_id: ISSUE_INTEGRATION_TESTS,
	},
	// PRD #95 internal: #264 blocks #265 and #266 (mirrors GitHub reference image)
	{
		id: 'mock-dep-4',
		blocker_issue_id: ISSUE_NOTIF_SOUND_FIX,
		blocked_issue_id: ISSUE_NOTIF_PACK_CREATOR,
	},
	{
		id: 'mock-dep-5',
		blocker_issue_id: ISSUE_NOTIF_SOUND_FIX,
		blocked_issue_id: ISSUE_NOTIF_TRIGGERS,
	},
	// PRD #90 internal: adapter blocks tool cards
	{
		id: 'mock-dep-6',
		blocker_issue_id: ISSUE_SESS_ADAPTER,
		blocked_issue_id: ISSUE_SESS_TOOL_CARDS,
	},
	// Cross-PRD: Sessions adapter blocks Notifications triggers
	{
		id: 'mock-dep-7',
		blocker_issue_id: ISSUE_SESS_ADAPTER,
		blocked_issue_id: ISSUE_NOTIF_TRIGGERS,
	},
	// PRD #94 internal: AI config UI blocks skill controls
	{
		id: 'mock-dep-8',
		blocker_issue_id: ISSUE_AI_CONFIG_UI,
		blocked_issue_id: ISSUE_AI_SKILL_CONTROLS,
	},
	// Cross-PRD: AI config UI blocks Sessions tool cards (need provider configured first)
	{
		id: 'mock-dep-9',
		blocker_issue_id: ISSUE_AI_CONFIG_UI,
		blocked_issue_id: ISSUE_SESS_TOOL_CARDS,
	},
];

// ─── Sessions ─────────────────────────────────────────────────────────────────

export const MOCK_SESSIONS: Session[] = [
	{
		id: 'mock-session-running',
		issue_id: ISSUE_AUTH_MIDDLEWARE,
		provider: 'claude-code',
		state: 'running',
		pid: 12345,
		cli_session_id: 'ses_abc123',
		started_at: '2026-05-03T09:00:00Z',
		ended_at: null,
		cost_usd: 0.42,
		token_count: 15200,
		original_intent: 'Refactor the auth middleware to use OAuth2 tokens',
		last_prompt: 'Continue with the token refresh logic',
		last_response_summary: 'Implementing token refresh with exponential backoff...',
		execution_phase: 'tdd',
		source: 'spawned',
		working_directory: 'C:/_MP_projects/worktrees/42-refactor-auth-middleware',
	},
	{
		id: 'mock-session-needs-input',
		issue_id: ISSUE_DARK_MODE,
		provider: 'claude-code',
		state: 'needs-input',
		pid: 12346,
		cli_session_id: 'ses_def456',
		started_at: '2026-05-03T08:30:00Z',
		ended_at: null,
		cost_usd: 0.28,
		token_count: 9800,
		original_intent: 'Add dark mode toggle component',
		last_prompt: null,
		last_response_summary: 'Should the toggle persist preference to localStorage or DB?',
		execution_phase: 'analyzing',
		source: 'spawned',
		working_directory: 'C:/_MP_projects/worktrees/55-dark-mode-toggle',
	},
	{
		id: 'mock-session-finished',
		issue_id: ISSUE_CI_PIPELINE,
		provider: 'claude-code',
		state: 'finished',
		pid: null,
		cli_session_id: 'ses_ghi789',
		started_at: '2026-05-02T14:00:00Z',
		ended_at: '2026-05-02T14:45:00Z',
		cost_usd: 1.05,
		token_count: 42000,
		original_intent: 'Fix E2E test timeouts in CI',
		last_prompt: null,
		last_response_summary:
			'Increased Playwright timeout and added retry logic for flaky tests.',
		execution_phase: 'none',
		source: 'adopted',
		working_directory: 'C:/_MP_projects/worktrees/71-ci-timeout-fix',
	},
	{
		id: 'mock-session-codex',
		issue_id: ISSUE_DARK_MODE,
		provider: 'codex',
		state: 'running',
		pid: 12347,
		cli_session_id: 'thread_0199a213',
		started_at: '2026-05-04T10:00:00Z',
		ended_at: null,
		cost_usd: 0.15,
		token_count: 5400,
		original_intent: 'Generate unit tests for dark mode toggle',
		last_prompt: 'Add tests for theme persistence',
		last_response_summary: 'Writing vitest specs for localStorage theme save/load...',
		execution_phase: 'tdd',
		source: 'spawned',
		working_directory: 'C:/_MP_projects/worktrees/55-dark-mode-toggle',
	},
];

// ─── Actions ──────────────────────────────────────────────────────────────────

export const MOCK_ACTIONS: Action[] = [
	{
		id: 'mock-action-editor',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Open in VS Code',
		icon: 'code',
		command_template: 'code {{worktree_folder}}',
		sort_order: 0,
		visible: true,
	},
	{
		id: 'mock-action-tests',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Run Tests',
		icon: 'test-tube',
		command_template: 'cd {{worktree_folder}} && pnpm test',
		sort_order: 1,
		visible: true,
	},
	{
		id: 'mock-action-deploy',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Deploy Preview',
		icon: 'rocket',
		command_template: 'cd {{worktree_folder}} && pnpm deploy:preview',
		sort_order: 2,
		visible: true,
	},
];

// ─── Color Palettes ──────────────────────────────────────────────────────────

export const MOCK_COLOR_PALETTES: ColorPalette[] = [
	{
		id: PALETTE_VIVID,
		name: 'Vivid',
		colors: [
			'#ef4444',
			'#f97316',
			'#eab308',
			'#22c55e',
			'#10b981',
			'#06b6d4',
			'#3b82f6',
			'#8b5cf6',
		],
		is_built_in: true,
	},
	{
		id: 'palette-pastel',
		name: 'Pastel',
		colors: [
			'#fca5a5',
			'#fdba74',
			'#fde047',
			'#86efac',
			'#6ee7b7',
			'#67e8f9',
			'#93c5fd',
			'#c4b5fd',
		],
		is_built_in: true,
	},
];

// ─── Git Status Caches ───────────────────────────────────────────────────────

export const MOCK_GIT_STATUSES: GitStatusCache[] = [
	{
		issue_id: ISSUE_AUTH_MIDDLEWARE,
		branch_status: 'active',
		pr_state: 'open',
		pr_number: 101,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/101',
		github_issue_state: 'open',
		behind_base_count: 2,
		merge_conflict: false,
		has_local_changes: true,
		ahead_remote_count: 3,
		fetched_at: '2026-05-03T09:00:00Z',
		pr_ci_status: 'passed',
	},
	{
		issue_id: ISSUE_DARK_MODE,
		branch_status: 'active',
		pr_state: 'draft',
		pr_number: 105,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/105',
		github_issue_state: 'open',
		behind_base_count: 0,
		merge_conflict: false,
		has_local_changes: false,
		ahead_remote_count: 0,
		fetched_at: '2026-05-03T08:30:00Z',
		pr_ci_status: 'running',
	},
	{
		issue_id: ISSUE_CI_PIPELINE,
		branch_status: 'active',
		pr_state: 'approved',
		pr_number: 110,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/110',
		github_issue_state: 'open',
		behind_base_count: 0,
		merge_conflict: false,
		has_local_changes: false,
		ahead_remote_count: 0,
		fetched_at: '2026-05-03T08:00:00Z',
		pr_ci_status: 'passed',
	},
	{
		issue_id: ISSUE_PR_MERGED,
		branch_status: 'active',
		pr_state: 'merged',
		pr_number: 115,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/115',
		github_issue_state: 'closed',
		behind_base_count: 0,
		merge_conflict: false,
		has_local_changes: false,
		ahead_remote_count: 0,
		fetched_at: '2026-05-03T12:00:00Z',
		pr_ci_status: 'passed',
	},
	{
		issue_id: ISSUE_CONFLICT,
		branch_status: 'active',
		pr_state: 'review-requested',
		pr_number: 118,
		pr_url: 'https://github.com/MartinoPolo/Grovekeeper/pull/118',
		github_issue_state: 'open',
		behind_base_count: 7,
		merge_conflict: true,
		has_local_changes: true,
		ahead_remote_count: 5,
		fetched_at: '2026-05-03T13:00:00Z',
		pr_ci_status: 'failed',
	},
];

// ─── Label Shape Mappings ─────────────────────────────────────────────────────

export const MOCK_LABEL_SHAPE_MAPPINGS: LabelShapeMapping[] = [
	{
		id: 'mock-lsm-auth',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		label_name: 'auth',
		tree_shape: 'oak',
		color: '#ef4444',
		priority_order: 0,
	},
	{
		id: 'mock-lsm-ui',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		label_name: 'ui',
		tree_shape: 'birch',
		color: '#8b5cf6',
		priority_order: 1,
	},
	{
		id: 'mock-lsm-perf',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		label_name: 'performance',
		tree_shape: 'willow',
		color: '#f97316',
		priority_order: 2,
	},
];

// ─── Notification Configs ─────────────────────────────────────────────────────

export const MOCK_NOTIFICATION_CONFIGS: NotificationConfig[] = [
	// Critical
	{
		event_type: 'session.needs-input',
		importance_tier: 'critical',
		sound_enabled: true,
		sound_file: 'grove/needs_input.wav',
		toast_enabled: true,
		window_flash_enabled: true,
	},
	{
		event_type: 'session.end',
		importance_tier: 'critical',
		sound_enabled: true,
		sound_file: 'grove/session_end.wav',
		toast_enabled: true,
		window_flash_enabled: true,
	},
	// Important
	{
		event_type: 'session.error',
		importance_tier: 'important',
		sound_enabled: true,
		sound_file: 'grove/error.wav',
		toast_enabled: true,
		window_flash_enabled: true,
	},
	{
		event_type: 'merge.conflict',
		importance_tier: 'important',
		sound_enabled: true,
		sound_file: 'grove/conflict.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'resource.limit',
		importance_tier: 'important',
		sound_enabled: true,
		sound_file: 'grove/error.wav',
		toast_enabled: true,
		window_flash_enabled: true,
	},
	{
		event_type: 'pr.ready',
		importance_tier: 'important',
		sound_enabled: true,
		sound_file: 'grove/ready.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	// Normal
	{
		event_type: 'session.start',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/start.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'task.complete',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/complete.wav',
		toast_enabled: false,
		window_flash_enabled: false,
	},
	{
		event_type: 'task.acknowledge',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/acknowledge.wav',
		toast_enabled: false,
		window_flash_enabled: false,
	},
	{
		event_type: 'pr.merged',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/merged.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'pr.review-requested',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/ready.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'branch.behind-base',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/acknowledge.wav',
		toast_enabled: false,
		window_flash_enabled: false,
	},
	{
		event_type: 'github.issue-assigned',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/notification.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'github.trigger-received',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/start.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
	{
		event_type: 'achievement.unlocked',
		importance_tier: 'normal',
		sound_enabled: false,
		sound_file: 'grove/achievement.wav',
		toast_enabled: true,
		window_flash_enabled: false,
	},
];

// ─── Assigned Issues ──────────────────────────────────────────────────────────

const MOCK_ASSIGNED_ISSUES: AssignedIssue[] = [
	{
		number: 42,
		title: 'Refactor auth middleware for OAuth2',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/42',
		labels: [{ name: 'auth', color: 'ef4444' }],
		parent_issue_number: 89,
	},
	{
		number: 55,
		title: 'Implement dark mode toggle',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/55',
		labels: [
			{ name: 'ui', color: '8b5cf6' },
			{ name: 'theme', color: '6366f1' },
		],
		parent_issue_number: 254,
	},
	{
		number: 78,
		title: 'Add onboarding wizard for new users',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/78',
		labels: [{ name: 'ui', color: '8b5cf6' }],
		parent_issue_number: null,
	},
	{
		number: 101,
		title: 'Wire notification event triggers from source points',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/101',
		labels: [
			{ name: 'AFK', color: '1D76DB' },
			{ name: 'task', color: '0E8A16' },
		],
		parent_issue_number: 95,
	},
	{
		number: 135,
		title: 'Build character pack creator with sound assignment',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/135',
		labels: [
			{ name: 'design-needed', color: 'E8820C' },
			{ name: 'HITL', color: 'FBCA04' },
		],
		parent_issue_number: 95,
	},
	{
		number: 200,
		title: 'Fix sound engine: Tokio crash and MP3 support',
		state: 'open',
		url: 'https://github.com/MartinoPolo/Grovekeeper/issues/200',
		labels: [{ name: 'bug', color: 'd73a4a' }],
		parent_issue_number: null,
	},
];

export const MOCK_ASSIGNED_ISSUES_RESULT: AssignedIssuesResult = {
	issues: MOCK_ASSIGNED_ISSUES,
	has_more: false,
};

// ─── Overview Data ────────────────────────────────────────────────────────────

export const MOCK_OVERVIEW_DATA: OverviewWorkspaceData[] = [
	{
		dashboard_id: DASHBOARD_GROVEKEEPER,
		name: 'Grovekeeper',
		github_repo: 'MartinoPolo/Grovekeeper',
		local_folder: 'C:/_MP_projects/Grovekeeper',
		color_palette_id: PALETTE_VIVID,
		accent_color: 'oklch(0.580 0.096 134)',
		open_issue_count: 10,
		active_session_count: 3,
		last_activity: new Date().toISOString(),
		total_cost_usd: 4.82,
		hitl_count: 0,
		open_pr_count: 2,
		prs_needing_attention: 0,
		afk_loop_status: 'running',
		default_branch: 'dev',
		worktree_count: 5,
		afk_ready_count: 3,
		prd_count: 3,
		prd_completed_subs: 12,
		prd_total_subs: 31,
		status: 'active',
	},
	{
		dashboard_id: 'dash-codeburn',
		name: 'codeburn',
		github_repo: 'MartinoPolo/codeburn',
		local_folder: 'C:/_MP_projects/codeburn',
		color_palette_id: null,
		accent_color: 'oklch(0.570 0.130 235)',
		open_issue_count: 7,
		active_session_count: 1,
		last_activity: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
		total_cost_usd: 2.15,
		hitl_count: 2,
		open_pr_count: 4,
		prs_needing_attention: 0,
		afk_loop_status: 'off',
		default_branch: 'main',
		worktree_count: 3,
		afk_ready_count: 1,
		prd_count: 2,
		prd_completed_subs: 8,
		prd_total_subs: 15,
		status: 'active',
	},
	{
		dashboard_id: 'dash-orchard-api',
		name: 'orchard-api',
		github_repo: 'MartinoPolo/orchard-api',
		local_folder: 'C:/_MP_projects/orchard-api',
		color_palette_id: null,
		accent_color: 'oklch(0.690 0.165 55)',
		open_issue_count: 4,
		active_session_count: 0,
		last_activity: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
		total_cost_usd: 0.92,
		hitl_count: 0,
		open_pr_count: 1,
		prs_needing_attention: 1,
		afk_loop_status: 'off',
		default_branch: 'main',
		worktree_count: 2,
		afk_ready_count: 0,
		prd_count: 1,
		prd_completed_subs: 3,
		prd_total_subs: 10,
		status: 'active',
	},
	{
		dashboard_id: 'dash-moss-cli',
		name: 'moss-cli',
		github_repo: 'MartinoPolo/moss-cli',
		local_folder: 'C:/_MP_projects/moss-cli',
		color_palette_id: null,
		accent_color: 'oklch(0.560 0.150 320)',
		open_issue_count: 3,
		active_session_count: 0,
		last_activity: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
		total_cost_usd: 0,
		hitl_count: 0,
		open_pr_count: 0,
		prs_needing_attention: 0,
		afk_loop_status: 'off',
		default_branch: 'main',
		worktree_count: 1,
		afk_ready_count: 0,
		prd_count: 0,
		prd_completed_subs: 0,
		prd_total_subs: 0,
		status: 'active',
	},
	{
		dashboard_id: 'dash-fern-ui',
		name: 'fern-ui',
		github_repo: null,
		local_folder: null,
		color_palette_id: null,
		accent_color: 'oklch(0.620 0.110 195)',
		open_issue_count: 0,
		active_session_count: 0,
		last_activity: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
		total_cost_usd: null,
		hitl_count: 0,
		open_pr_count: 0,
		prs_needing_attention: 0,
		afk_loop_status: 'off',
		default_branch: null,
		worktree_count: 0,
		afk_ready_count: 0,
		prd_count: 0,
		prd_completed_subs: 0,
		prd_total_subs: 0,
		status: 'active',
	},
	{
		dashboard_id: 'dash-sapling',
		name: 'sapling',
		github_repo: 'MartinoPolo/sapling',
		local_folder: 'C:/_MP_projects/sapling',
		color_palette_id: null,
		accent_color: 'oklch(0.640 0.155 15)',
		open_issue_count: 12,
		active_session_count: 0,
		last_activity: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
		total_cost_usd: 3.41,
		hitl_count: 0,
		open_pr_count: 3,
		prs_needing_attention: 0,
		afk_loop_status: 'off',
		default_branch: 'main',
		worktree_count: 4,
		afk_ready_count: 5,
		prd_count: 1,
		prd_completed_subs: 0,
		prd_total_subs: 6,
		status: 'active',
	},
];

// ─── Workspace Commands ──────────────────────────────────────────────────────

export const MOCK_WORKSPACE_COMMANDS: WorkspaceCommand[] = [
	{
		id: 'mock-cmd-dev-server',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		category: 'server',
		name: 'Dev Server',
		command: 'pnpm tauri dev',
		port_pattern: 'Local:\\s+http://localhost:(\\d+)',
		expected_exit_code: 0,
		sort_order: 0,
	},
	{
		id: 'mock-cmd-frontend-only',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		category: 'server',
		name: 'Frontend Only',
		command: 'pnpm dev',
		port_pattern: 'localhost:(\\d+)',
		expected_exit_code: 0,
		sort_order: 1,
	},
	{
		id: 'mock-cmd-check-all',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		category: 'check',
		name: 'Full Check',
		command: 'pnpm check:all',
		port_pattern: null,
		expected_exit_code: 0,
		sort_order: 0,
	},
	{
		id: 'mock-cmd-test',
		dashboard_id: DASHBOARD_GROVEKEEPER,
		category: 'check',
		name: 'Unit Tests',
		command: 'pnpm test',
		port_pattern: null,
		expected_exit_code: 0,
		sort_order: 1,
	},
];

// ─── Window Bindings ──────────────────────────────────────────────────────────

export const MOCK_WINDOW_BINDINGS: WindowWorkspaceBinding[] = [];

// ─── Keyboard Shortcuts ───────────────────────────────────────────────────────

export const MOCK_CUSTOM_BINDINGS: KeyboardShortcut[] = [];

// ─── Prunable Issues ──────────────────────────────────────────────────────────

export const MOCK_PRUNABLE_ISSUES: PrunableIssue[] = [];

// ─── Sync Result ──────────────────────────────────────────────────────────────

export const MOCK_SYNC_RESULT: SyncAllResult = { synced_count: 3, errors: [] };

// ─── Usage Dashboard ──────────────────────────────────────────────────────────

export const MOCK_USAGE_DASHBOARD = {
	stats: {
		total_cost_usd: 12.84,
		session_count: 47,
		one_shot_rate: 74.0,
		cache_hit_ratio: 68.0,
		cost_delta_percent: -18.0,
		session_count_delta: 9,
	},
	time_bucket_costs: Array.from({ length: 30 }, (_, i) => ({
		date: `2026-04-${String(i + 1).padStart(2, '0')}`,
		cost_usd: +(Math.random() * 1.5).toFixed(2),
		session_count: Math.floor(Math.random() * 5) + 1,
	})),
	grouped_costs: [
		{ date: '2026-04-28', group: 'claude-opus-4-6', cost_usd: 0.82, session_count: 3 },
		{ date: '2026-04-28', group: 'claude-sonnet-4-6', cost_usd: 0.34, session_count: 5 },
		{ date: '2026-04-29', group: 'claude-opus-4-6', cost_usd: 1.1, session_count: 4 },
		{ date: '2026-04-29', group: 'claude-sonnet-4-6', cost_usd: 0.21, session_count: 2 },
		{ date: '2026-04-29', group: 'claude-haiku-4-5', cost_usd: 0.05, session_count: 1 },
		{ date: '2026-04-30', group: 'claude-opus-4-6', cost_usd: 0.95, session_count: 3 },
		{ date: '2026-04-30', group: 'claude-sonnet-4-6', cost_usd: 0.41, session_count: 4 },
	],
	activity_breakdown: [
		{ category: 'coding', cost_usd: 4.2, turn_count: 89, one_shot_percent: 82.0 },
		{ category: 'debugging', cost_usd: 2.8, turn_count: 52, one_shot_percent: 61.0 },
		{ category: 'refactoring', cost_usd: 1.9, turn_count: 31, one_shot_percent: 90.0 },
		{ category: 'testing', cost_usd: 1.4, turn_count: 28, one_shot_percent: 78.0 },
		{ category: 'exploration', cost_usd: 1.1, turn_count: 24, one_shot_percent: 0.0 },
		{ category: 'planning', cost_usd: 0.8, turn_count: 18, one_shot_percent: 0.0 },
		{ category: 'conversation', cost_usd: 0.64, turn_count: 15, one_shot_percent: 0.0 },
	],
	top_sessions: [
		{
			session_id: 's1',
			issue_name: 'Auth middleware rewrite',
			issue_number: 42,
			cost_usd: 1.42,
			turn_count: 28,
			tool_call_count: 67,
			started_at: '2026-04-24T14:30:00Z',
		},
		{
			session_id: 's2',
			issue_name: 'Dark mode toggle',
			issue_number: 15,
			cost_usd: 0.98,
			turn_count: 15,
			tool_call_count: 34,
			started_at: '2026-04-22T10:00:00Z',
		},
		{
			session_id: 's3',
			issue_name: 'Perf audit',
			issue_number: 7,
			cost_usd: 0.87,
			turn_count: 12,
			tool_call_count: 29,
			started_at: '2026-04-20T09:00:00Z',
		},
		{
			session_id: 's4',
			issue_name: 'CI pipeline fix',
			issue_number: 3,
			cost_usd: 0.76,
			turn_count: 9,
			tool_call_count: 22,
			started_at: '2026-04-18T16:00:00Z',
		},
		{
			session_id: 's5',
			issue_name: null,
			issue_number: null,
			cost_usd: 0.54,
			turn_count: 7,
			tool_call_count: 15,
			started_at: '2026-04-15T11:00:00Z',
		},
	],
	tool_usage: [
		{ tool_name: 'Read', call_count: 342 },
		{ tool_name: 'Edit', call_count: 187 },
		{ tool_name: 'Bash', call_count: 156 },
		{ tool_name: 'Grep', call_count: 134 },
		{ tool_name: 'Write', call_count: 89 },
		{ tool_name: 'Glob', call_count: 76 },
		{ tool_name: 'Agent', call_count: 42 },
		{ tool_name: 'WebSearch', call_count: 18 },
		{ tool_name: 'mcp__svelte', call_count: 12 },
		{ tool_name: 'TaskCreate', call_count: 8 },
	],
	pricing_available: true,
};

export const MOCK_ACHIEVEMENTS = [
	{
		kind: 'first-seed',
		display_name: 'First Seed',
		description: 'Created your first issue',
		threshold: 1,
		progress: 1,
		unlocked_at: '2026-04-01T10:00:00Z',
	},
	{
		kind: 'created-10-trees',
		display_name: 'Created 10 Trees',
		description: 'Created 10 issues',
		threshold: 10,
		progress: 12,
		unlocked_at: '2026-04-15T14:00:00Z',
	},
	{
		kind: 'created-50-trees',
		display_name: 'Created 50 Trees',
		description: 'Created 50 issues',
		threshold: 50,
		progress: 12,
		unlocked_at: null,
	},
	{
		kind: 'green-thumb',
		display_name: 'Green Thumb',
		description: 'Completed 10 sessions via Grovekeeper',
		threshold: 10,
		progress: 10,
		unlocked_at: '2026-04-20T16:00:00Z',
	},
	{
		kind: 'forest-keeper',
		display_name: 'Forest Keeper',
		description: 'Resolved 5 HITL issues',
		threshold: 5,
		progress: 3,
		unlocked_at: null,
	},
	{
		kind: 'conflict-resolver',
		display_name: 'Conflict Resolver',
		description: 'Auto-resolved 3 merge conflicts',
		threshold: 3,
		progress: 1,
		unlocked_at: null,
	},
	{
		kind: 'one-shot-wonder',
		display_name: 'One-Shot Wonder',
		description: '5 sessions with 100% one-shot rate',
		threshold: 5,
		progress: 5,
		unlocked_at: '2026-05-01T09:00:00Z',
	},
	{
		kind: 'cache-master',
		display_name: 'Cache Master',
		description: 'A session with 90%+ cache hit ratio',
		threshold: 1,
		progress: 1,
		unlocked_at: '2026-04-25T12:00:00Z',
	},
	{
		kind: 'big-spender',
		display_name: 'Big Spender',
		description: 'Spent $100 total on AI sessions',
		threshold: 100,
		progress: 12,
		unlocked_at: null,
	},
	{
		kind: 'speed-runner',
		display_name: 'Speed Runner',
		description: 'Completed a session in under 60 seconds',
		threshold: 1,
		progress: 0,
		unlocked_at: null,
	},
];

export const MOCK_IMPORT_SUMMARY = {
	providers: [
		{ provider: 'claude-code', sessions_imported: 142, sessions_skipped: 0 },
		{ provider: 'cursor', sessions_imported: 89, sessions_skipped: 3 },
		{ provider: 'codex', sessions_imported: 16, sessions_skipped: 0 },
	],
	total_sessions: 247,
	total_skipped: 3,
};

// ─── Settings ─────────────────────────────────────────────────────────────────

export const MOCK_USER_SETTINGS: Record<string, string> = {
	theme_mode: 'system',
	accent_color: 'moss',
	username: 'User',
	user_initials: 'U',
	startup_behavior: 'overview',
	chart_color_theme: 'monochrome',
	language: 'en',
	notification_volume: '0.7',
	issue_card_variant: 'refined-horizon',
	issue_card_button_color: 'issue-color',
	issue_card_priority_position: 'header-right',
	issue_card_badge_style: 'borderless-dark',
	issue_card_label_tint: '20',
	issue_card_overlay_glow: '150',
	issue_card_gradient_reach: '60',
	issue_card_color_saturation: '150',
	issue_card_header_saturation: '85',
	issue_card_radial_intensity: '75',
};
