import { ACTION_IDS, type ActionId, type ContextualActionDefinition } from './types.js';

export const ACTION_POOL: Record<ActionId, ContextualActionDefinition> = {
	[ACTION_IDS.Run]: {
		id: ACTION_IDS.Run,
		label: 'Run',
		icon: 'play',
		invocationType: 'agent',
		commandTemplate: 'mp-execute #{{issue_number}}',
	},
	[ACTION_IDS.Hitl]: {
		id: ACTION_IDS.Hitl,
		label: 'HITL',
		icon: 'hand',
		invocationType: 'agent',
		commandTemplate: 'mp-hitl #{{issue_number}}',
	},
	[ACTION_IDS.Review]: {
		id: ACTION_IDS.Review,
		label: 'Review',
		icon: 'eye',
		invocationType: 'agent',
		commandTemplate: 'mp-review scope=branch',
	},
	[ACTION_IDS.CheckAndFix]: {
		id: ACTION_IDS.CheckAndFix,
		label: 'Check & Fix',
		icon: 'wrench',
		invocationType: 'agent',
		commandTemplate: 'mp-check-fix',
	},
	[ACTION_IDS.Commit]: {
		id: ACTION_IDS.Commit,
		label: 'Commit',
		icon: 'git-commit-vertical',
		invocationType: 'agent',
		commandTemplate: 'mp-commit',
	},
	[ACTION_IDS.CommitAndPush]: {
		id: ACTION_IDS.CommitAndPush,
		label: 'Commit & Push',
		icon: 'git-commit-vertical',
		invocationType: 'agent',
		commandTemplate: 'mp-commit-push',
	},
	[ACTION_IDS.CommitPushAndPr]: {
		id: ACTION_IDS.CommitPushAndPr,
		label: 'Commit, Push & PR',
		icon: 'git-pull-request',
		invocationType: 'agent',
		commandTemplate: 'mp-commit-push-pr',
	},
	[ACTION_IDS.CreatePr]: {
		id: ACTION_IDS.CreatePr,
		label: 'Create PR',
		icon: 'git-pull-request-create',
		invocationType: 'agent',
		commandTemplate: 'mp-pr',
	},
	[ACTION_IDS.CodeClean]: {
		id: ACTION_IDS.CodeClean,
		label: 'Code Clean',
		icon: 'sparkles',
		invocationType: 'agent',
		commandTemplate: 'mp-code-clean',
	},
	[ACTION_IDS.Push]: {
		id: ACTION_IDS.Push,
		label: 'Push',
		icon: 'arrow-up',
		invocationType: 'deterministic',
		commandTemplate: 'git push',
	},
	[ACTION_IDS.Merge]: {
		id: ACTION_IDS.Merge,
		label: 'Merge',
		icon: 'git-merge',
		invocationType: 'deterministic',
		commandTemplate: 'gh pr merge',
	},
	[ACTION_IDS.SyncBase]: {
		id: ACTION_IDS.SyncBase,
		label: 'Sync Base',
		icon: 'refresh-cw',
		invocationType: 'agent',
		commandTemplate: 'mp-sync-base',
	},
	[ACTION_IDS.SetupWorktree]: {
		id: ACTION_IDS.SetupWorktree,
		label: 'Setup Worktree',
		icon: 'git-branch-plus',
		invocationType: 'deterministic',
		commandTemplate: null,
	},
	[ACTION_IDS.RemoveWorktree]: {
		id: ACTION_IDS.RemoveWorktree,
		label: 'Remove Worktree',
		icon: 'git-branch-minus',
		invocationType: 'deterministic',
		commandTemplate: null,
	},
	[ACTION_IDS.RetryWorktree]: {
		id: ACTION_IDS.RetryWorktree,
		label: 'Retry Worktree',
		icon: 'rotate-cw',
		invocationType: 'deterministic',
		commandTemplate: null,
	},
	[ACTION_IDS.ViewSession]: {
		id: ACTION_IDS.ViewSession,
		label: 'View Session',
		icon: 'monitor',
		invocationType: 'ui',
		commandTemplate: null,
	},
} as const satisfies Record<ActionId, ContextualActionDefinition>;
